#!/bin/bash
set_prefix() {
    local this=$(readlink -n -f "$1")
    prefix=$(dirname "${this}")
}
set_prefix "${0}"

as_run_location=$(find /opt/salome_meca -type f -name as_run -print | head -n 1 2>/dev/null)

$as_run_location $@
